version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: erp-postgres
    environment:
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: Neurolinx@2026
      POSTGRES_DB: erp_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata_new:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: erp-redis
    ports:
      - "6381:6379"
    restart: unless-stopped

  emqx:
    image: emqx:5
    container_name: erp-emqx
    ports:
      - "8885:8883"
      - "18085:18083"
      - "1885:1883"
    restart: unless-stopped

  erp-api:
    image: ghcr.io/neurolinxdeveloper-0369/erp-api:latest
    container_name: erp-api
    depends_on:
      - db
      - redis
    ports:
      - "8088:8080"
    restart: unless-stopped

  frontend:
    image: ghcr.io/neurolinxdeveloper-0369/erp-frontend:latest
    container_name: erp-frontend
    ports:
      - "8087:80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: erp-nginx
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: erp-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait {!}; done;'"
    restart: unless-stopped

volumes:
  pgdata_new:
  redis_data:
