spring.datasource.url=jdbc:postgresql://db:5432/erp_db
spring.datasource.username=erp_admin
spring.datasource.password=Neurolinx@2026
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=neurolinxdeveloper@gmail.com
spring.mail.password=jjqd fsfm wabf zzij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
