name: Build and Publish to GHCR

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: neurolinxdeveloper-0369/erp-api
  FRONTEND_IMAGE_NAME: neurolinxdeveloper-0369/erp-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push ERP API
        uses: docker/build-push-action@v4
        with:
          context: ./erp-api
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest

      - name: Build and push ERP Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./erp-frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

      - name: Deploy to VPS via Portainer Webhook
        run: |
          curl -k -X POST "https://portainer.neurolinx.in:9443/api/stacks/webhooks/bf8accf0-3003-461b-a437-0808ef8d78e2"
